export interface ArtCraftData {
  name: string;
  localName?: string;
  state: string;
  region?: string;
  district?: string;
  place: string;
  type: string;
  originPeriod: string;
  history: string;
  culturalSignificance: string;
  culturalBackground: string;
  materials: string;
  makingProcess: string;
  traditionalProducts: string;
  modernContext: string;
  coverImage?: string;
  status?: string;
}

export const indianArtCraftsData: ArtCraftData[] = [
  // 1. ANDHRA PRADESH - Srikalahasti Kalamkari & Kondapalli Toys
  {
    name: 'Srikalahasti Kalamkari',
    localName: 'శ్రీకాళహస్తి కలంకారీ / श्रीकालहस्ती कलमकारी',
    state: 'Andhra Pradesh',
    region: 'Rayalaseema',
    district: 'Tirupati (formerly Chittoor)',
    place: 'Srikalahasti',
    type: 'Traditional Painting & Natural Dye Textile',
    originPeriod: 'Origin period: Believed to date back to the Vijayanagara Empire (c. 14th–16th century CE), flourishing around temple precincts.',
    history: 'Kalamkari derives from "kalam" (bamboo reed pen) and "kari" (craftsmanship). The Srikalahasti tradition developed around the sacred Swarnamukhi river and the ancient Srikalahasteeswara temple. Temple patron kings of the Vijayanagara dynasty commissioned artists to paint large cloth scrolls (vrikshachitra and temple hangings) depicting narratives from the Ramayana, Mahabharata, and Puranas for devotees during seasonal temple gatherings.',
    culturalSignificance: 'Regarded as a sacred ritual art form rather than mere decoration. The narrative scrolls served as pictorial sermons narrating divine stories in temples. The Swarnamukhi river water rich in minerals acts as a natural mordant fixing the earthen colors.',
    culturalBackground: 'Practiced for centuries by the Balija and surrounding artisanal communities who passed down the secret formulation of vegetable mordants and freehand bamboo styling across generations.',
    materials: 'Unbleached cotton (madaarpalam), bamboo stylus (kalam) with sheep-wool reservoir, myrobalan nuts (karakkaya), alum (potash alum), buffalo milk, natural madder root (surulpattai), indigo, and pomegranate peel.',
    makingProcess: '1. Raw unbleached cotton is treated with buffalo milk and crushed myrobalan nut paste to absorb dyes evenly. 2. Outline sketch is drawn freehand using charred tamarind twigs. 3. Fine bamboo kalam filled with fermented iron-jaggery solution (kasimi) creates jet-black outlines. 4. Alum solution mordant is applied where red shades are needed. 5. Cloth is boiled with madder root. 6. Repeated river washing and sun-bleaching. 7. Yellow and blue vegetable extracts filled in for foliage and ornaments.',
    traditionalProducts: 'Temple backdrop hangings (Kalamkari Toranam), scroll paintings, Ramayana depiction panels, sarees, dupattas, wall tapestries.',
    modernContext: 'Awarded Geographical Indication (GI) status under Andhra Pradesh in 2006. Modern artisans face competition from chemical screen-prints, but government-supported societies under the Ministry of Textiles preserve natural dye authenticity.',
    coverImage: 'https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },
  {
    name: 'Kondapalli Toys',
    localName: 'కొండపల్లి బొమ్మలు / कोंडापल्ली खिलौने',
    state: 'Andhra Pradesh',
    region: 'Coastal Andhra',
    district: 'NTR district (formerly Krishna)',
    place: 'Kondapalli',
    type: 'Traditional Woodcraft & Toy Making',
    originPeriod: 'Origin period: Believed to date back to the 16th century CE; artisan lore associates their settlement with migration during the Vijayanagara period.',
    history: 'Kondapalli toys originated in the historic village of Kondapalli near Vijayawada. According to local historical chronicles and oral tradition, the artisan community known as the Aryakshatriyas (or Nakarshalu) trace their heritage to the ancient sculptor Muktharishi and migrated to Andhra during the reign of Vijayanagara kings and Anapotha Reddy of the Kondaveedu dynasty.',
    culturalSignificance: 'Integral to the festive celebrations of Navratri and Sankranti, specifically the traditional "Bommala Koluvu" (doll arrangement) displayed in households. Iconic depictions include Dashavatara, bullock carts, rural farmers, and mythological scenes.',
    culturalBackground: 'Carried forward by hereditary craftsman families living in the Toy Colony of Kondapalli village.',
    materials: 'Soft local wood known as Tella Poniki (Givotia rottleriformis), makku paste (tamarind seed powder mixed with sawdust and gum), oil colors, vegetable dyes, and water tempera.',
    makingProcess: '1. Seasoned Tella Poniki softwood is hand-sawn into raw blocks. 2. Chisel and specialized wood-knives carve distinct body components (head, torso, limbs). 3. Components joined with tamarind-seed paste (makku). 4. Seams smoothened with makku paste. 5. Base coat of white zinc applied. 6. Intricate hand painting of features with fine brushes. 7. Clear protective lacquer coat.',
    traditionalProducts: 'Ambari elephant with Mahout, Bullock cart, Dashavatara doll sets, Palm toddy tapper, Village elders.',
    modernContext: 'Conferred Geographical Indication (GI) registration in 2007. Sustainable sourcing of Tella Poniki wood is actively supported by state forestry departments.',
    coverImage: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 2. ARUNACHAL PRADESH - Thangka Painting & Monpa Wood Carving
  {
    name: 'Monpa Wood Carving & Mask Making',
    localName: 'मोन्पा काष्ठ नक्काशी / Monpa Wooden Masks',
    state: 'Arunachal Pradesh',
    region: 'Western Kameng & Tawang',
    district: 'Tawang & West Kameng',
    place: 'Tawang & Dirang',
    type: 'Traditional Woodcraft & Ritual Mask Art',
    originPeriod: 'Origin period: Believed to date back to the 17th century CE with the establishment of Tawang Monastery (Gaden Namgyal Lhatse).',
    history: 'The Monpa people inhabiting the high Himalayas of Tawang and West Kameng developed intricate woodcraft closely tied to Mahayana Buddhism. Monastic festivals such as Torgya and Losar required expressive wooden masks representing Buddhist deities, guardian spirits, and protective animals.',
    culturalSignificance: 'Sacred ritual dance (Chham) performed by monks in the courtyard of Tawang Monastery requires authentic hand-carved Monpa masks to invoke spiritual protection and dispel negative forces.',
    culturalBackground: 'Practiced by master woodworkers belonging to the Monpa community residing in high-altitude Himalayan settlements.',
    materials: 'Local Himalayan softwoods (such as pine, birch, and rhododendron wood), natural mineral pigments, yak leather straps.',
    makingProcess: '1. Seasoned Himalayan wood block shaped with adze. 2. Detailed facial contours carved with fine gouges and chisels. 3. Natural animal glue and chalk primer applied. 4. Pigments brushed according to Tibetan Buddhist iconographic canons. 5. Varnish applied for ritual weather resistance.',
    traditionalProducts: 'Chham dance masks (Jawa, Keng Cham), carved low wooden tables (Choktse), ceremonial bowls (Daphne), butter churners.',
    modernContext: 'Certified as an endangered tribal heritage art protected by the Arunachal Pradesh Department of Cultural Affairs and Himalayan craft centers.',
    coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 3. ASSAM - Muga Silk Weaving & Majuli Mask Making
  {
    name: 'Sualkuchi Muga Silk Weaving',
    localName: 'সাঁলকুছিৰ মুগা ৰেচম / असमिया मुगा रेशम',
    state: 'Assam',
    region: 'Lower Assam / Brahmaputra Valley',
    district: 'Kamrup (Rural)',
    place: 'Sualkuchi',
    type: 'Textile Weaving & Sericulture',
    originPeriod: 'Origin period: Documented since ancient times; fostered by the Ahom dynasty (13th–18th century CE) as royal attire.',
    history: 'Sualkuchi is acclaimed as the "Manchester of Assam". Muga silk is derived from the endemic silkworm Antheraea assamensis fed on aromatic Som and Soalu leaves. Ahom rulers established royal workshops (Khels) making Muga garments exclusively reserved for royalty and nobility.',
    culturalSignificance: 'Muga silk’s natural golden tint is emblematic of Assamese bridal attire (Mekhela Chador) and Bihu festival celebrations. With every wash, the lustrous golden sheen enhances rather than fades.',
    culturalBackground: 'Practiced across Sualkuchi by multi-generational Assamese weavers using indigenous throw-shuttle and fly-shuttle pit looms.',
    materials: 'Natural golden Muga silk thread, bamboo reeds, wooden jacquard/drawloom fittings.',
    makingProcess: '1. Silkworms reared on Som trees. 2. Cocoons boiled and hand-reeled to yield unbroken golden filament. 3. Yarn spun and loaded onto bobbins. 4. Pit looms set with traditional Assamese jaapi and floral motifs (Kinkhap). 5. Hand-woven using traditional shuttle movement.',
    traditionalProducts: 'Muga Mekhela Chador, Riha, Gamosa, royal jackets, modern stoles.',
    modernContext: 'GI tagged in 2007 (one of India’s earliest silk GI registrations). State sericulture federations protect natural forest habitats of the wild silkworms.',
    coverImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 4. BIHAR - Madhubani / Mithila Painting
  {
    name: 'Madhubani Painting',
    localName: 'मधुबनी चित्रकला / मिथिला पेंटिंग',
    state: 'Bihar',
    region: 'Mithila',
    district: 'Madhubani',
    place: 'Madhubani, Jitwarpur & Ranti',
    type: 'Traditional Painting',
    originPeriod: 'Origin period: Traditionally associated with the Treta Yuga and epic Ramayana; historically documented as a living domestic wall art across generations.',
    history: 'Historically practiced by women of the Mithila region on freshly plastered mud and cow dung walls (Kohbar and Bhitti Chitra). It gained worldwide recognition after a major earthquake in 1934 revealed the spectacular interior murals to British officer William G. Archer.',
    culturalSignificance: 'Painted during weddings, births, and religious ceremonies to invoke prosperity and fertility. Iconic representations include Radha-Krishna, Shiva-Parvati, Sun and Moon, fish, lotus, and peacock motifs.',
    culturalBackground: 'Divided into traditional styles including Bharni (color-filled), Kachni (fine linework), Tantrik (spiritual symbols), and Godna (tattoo-inspired forms).',
    materials: 'Handmade paper treated with cow dung wash, fine bamboo nib pens, natural pigments from turmeric, lampblack, indigo, palash flowers, and aparajita.',
    makingProcess: '1. Handmade paper or cloth prepared with cow-dung water base. 2. Outlines drawn directly without preliminary pencil sketch using bamboo sticks. 3. Intricate parallel geometric lines and hatching added. 4. Natural pigments filled in without leaving empty space.',
    traditionalProducts: 'Kohbar wedding wall hangings, silk dupattas, framed art canvases, painted sarees, bookmark sets.',
    modernContext: 'Awarded GI certification in 2007. Master painters like Jagdamba Devi and Mahasundari Devi received Padma awards, establishing global acclaim.',
    coverImage: 'https://images.unsplash.com/photo-1582560475093-ba66accbc424?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 5. CHHATTISGARH - Bastar Dhokra Bell Metal
  {
    name: 'Bastar Dhokra Art',
    localName: 'बस्तर ढोकरा शिल्प / Bell Metal Lost Wax Casting',
    state: 'Chhattisgarh',
    region: 'Bastar',
    district: 'Bastar & Kondagaon',
    place: 'Kondagaon & Jagdalpur',
    type: 'Metal Casting & Bell Metal Craft',
    originPeriod: 'Origin period: Believed to date back over 4,000 years, retaining continuous bronze-age lost-wax casting technique akin to Mohenjo-daro Dancing Girl.',
    history: 'Dhokra is a traditional non-ferrous metal casting craft utilizing the cire-perdue (lost wax) process. The Ghadwa and Jhara tribal artisan communities of Bastar have practiced this art for millennia, crafting ritual deities, oil lamps, and tribal hunting scenes.',
    culturalSignificance: 'Essential to Bastar tribal culture and ancestor worship. Sculptures of village guardian deities (Mawli Devi, Danteshwari Devi) are cast for local shrines and annual Dussehra rituals.',
    culturalBackground: 'Practiced by the Ghadwa tribal community whose hereditary vocation revolves around bell-metal casting.',
    materials: 'Beeswax mixed with dammar (tree resin), clay from termite mounds, paddy husk, brass scrap, river sand, charcoal furnace.',
    makingProcess: '1. Core clay model prepared with river mud and paddy husk. 2. Pure beeswax threads pressed through wooden piston to form delicate decorative strands. 3. Wax threads wrapped precisely over clay core. 4. Outer clay shell applied and dried in shade. 5. Molten brass poured into channel, melting and displacing the wax. 6. Clay broken to reveal raw metal sculpture. 7. Hand-buffing with wire brush.',
    traditionalProducts: 'Tribal musicians, elephants with howdah, oil lamps (Diya), Mother Goddess figurines, animal totems.',
    modernContext: 'GI registered in 2008. Widely celebrated internationally for its timeless primitive elegance and sustainable zero-waste metallurgy.',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 6. GOA - Kaavi Kale Architectural Mural Art
  {
    name: 'Kaavi Kale Architectural Art',
    localName: 'कावी काळे / Kaavi Art of Konkan',
    state: 'Goa',
    region: 'Konkan',
    district: 'North & South Goa',
    place: 'Goa Velha, Ponda & Bicholim',
    type: 'Traditional Architectural Etching & Mural Art',
    originPeriod: 'Origin period: Believed to date back to the 16th century CE, flourishing across Konkan temple architecture.',
    history: 'Kaavi Kale is a unique monochrome architectural wall-etching art discovered along coastal Konkan shrines, temples, and Goan ancestral homes. Using reddish-brown laterite soil (Kaav), artisans plastered temple walls and engraved sacred motifs before the layer set.',
    culturalSignificance: 'Adorning temples dedicated to Shantadurga, Mangesh, and ancient Goan chapel facades, depicting sacred Mandalas, floral arabesques, and mythological narratives.',
    culturalBackground: 'Hereditary Goan craftsmen and temple stonemasons preserving coastal Konkan visual traditions.',
    materials: 'Kaav (deep red laterite clay rich in iron oxide), slaked lime (chuna) prepared from burnt seashells, river sand, and jaggery fermentation binder.',
    makingProcess: '1. Wall pre-coated with lime and sea-shell plaster. 2. Wet layer of red Kaav paste spread evenly. 3. Steel stylus or sharp bamboo points scratch away red coating while still wet to expose pure white lime beneath. 4. Surface buffed with smooth river pebbles.',
    traditionalProducts: 'Temple friezes, ancestral home doorway panels, decorative wall panels, terracotta tiles.',
    modernContext: 'State cultural conservation bodies are currently reviving endangered Kaavi artists through restoration of heritage temple murals.',
    coverImage: 'https://images.unsplash.com/photo-1590059390046-608b874495e8?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 7. GUJARAT - Rogan Art & Patan Patola
  {
    name: 'Rogan Art',
    localName: 'રોગન આર્ટ / रोगन कला',
    state: 'Gujarat',
    region: 'Kutch',
    district: 'Kutch',
    place: 'Nirona',
    type: 'Traditional Fabric Painting & Castor Oil Paste Craft',
    originPeriod: 'Origin period: Believed to date back approximately 300 years, introduced from Persia through Sindh into Kutch.',
    history: 'Rogan art is an extraordinarily rare craft of painting on fabric using boiled castor oil residue. Practiced by the Khatri community in Nirona village, the art was once near extinction until national recognition and diplomatic gifts brought it worldwide prominence.',
    culturalSignificance: 'Traditionally used to embellish bridal ghagras, bridal bedspreads, and ceremonial veils of local pastoral communities (such as Ahir and Rabari).',
    culturalBackground: 'Preserved exclusively by the Khatri Muslim artisan families of Nirona village in Kutch.',
    materials: 'Castor oil boiled continuously for over 48 hours to create sticky residue (Rogan), natural mineral pigments, cold water, metal rod stylus (kalam).',
    makingProcess: '1. Castor seed oil boiled outdoors for two days until gelatinous. 2. Mineral powders mixed into residue. 3. Artisan takes dollop of colored paste on palm, working with six-inch metal stylus to draw out hair-thin elastic threads without touching cloth. 4. Thread laid gently onto cloth. 5. Fabric folded down the center to mirror the wet impression symmetrically.',
    traditionalProducts: 'Tree of Life wall hangings, cushion covers, stoles, bridal veils, framed art pieces.',
    modernContext: 'Conferred National Awards and presented by Prime Minister Narendra Modi to foreign heads of state; protected under UNESCO cultural heritage promotion.',
    coverImage: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 8. HARYANA - Panipat Handloom Durries
  {
    name: 'Panipat Handloom Durries & Punja Weaving',
    localName: 'पानीपत की पंजा दरी / Panipat Handloom Durries',
    state: 'Haryana',
    region: 'North Haryana',
    district: 'Panipat',
    place: 'Panipat',
    type: 'Textile Weaving & Floor Coverings',
    originPeriod: 'Origin period: Believed to date back to the late medieval period; gained massive structured handloom prominence in the 19th century.',
    history: 'Panipat, known historically as the "Textile City" and "Weaver’s City", is the preeminent hub of traditional hand-woven flatweave rugs (Durries). Weavers utilize the traditional "Punja" (a heavy metallic comb-like claw) to firmly beat weft threads into dense, long-lasting geometric structures.',
    culturalSignificance: 'Historically gifted in rural Haryana households as part of bridal trousseaus, symbolizing domestic prosperity and familial warmth.',
    culturalBackground: 'Skilled weaving community consisting of master Ansari and regional Punjabi handloom weavers who settled post-partition.',
    materials: 'Raw cotton yarns, spun wool, natural dyes, heavy steel/wooden Punja combs, traditional horizontal frame looms.',
    makingProcess: '1. Cotton warp yarns tautly warped on horizontal ground loom. 2. Colored wool or cotton weft threads inserted by hand according to geometric graph designs. 3. Heavy metallic Punja comb beaten manually against each row to pack threads tightly. 4. Edges knotted and trimmed.',
    traditionalProducts: 'Striped and geometric Punja Durries, floor mats, prayer rugs, modern decorative dhurries.',
    modernContext: 'Recognized by the Ministry of Textiles; exported globally for eco-friendly interior design and sustainable organic cotton flatweaves.',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 9. HIMACHAL PRADESH - Chamba Rumal
  {
    name: 'Chamba Rumal',
    localName: 'चंबा रूमाल / Chamba Needlework',
    state: 'Himachal Pradesh',
    region: 'Chamba Valley',
    district: 'Chamba',
    place: 'Chamba',
    type: 'Double-Sided Needlework & Silk Embroidery',
    originPeriod: 'Origin period: Believed to date back to the 17th–18th century CE under the patronage of Raja Umed Singh of Chamba.',
    history: 'Chamba Rumal is a rare form of needlework where paintings of the Pahari miniature school are translated onto unbleached malmal cloth using untwisted silk threads. Uniquely, the double-satin stitch (Dorukha) ensures that the embroidery appears identical on both sides.',
    culturalSignificance: 'Traditionally exchanged as auspicious covers for wedding offerings and gift platters between bride and groom families, depicting Krishna Leela, Raas Mandala, and wedding processions.',
    culturalBackground: 'Pioneered by royal women and noble families of the Chamba kingdom, collaborating with court miniature painters.',
    materials: 'Fine unbleached cotton (Malmal or Khaddar), untwisted pure silk floss (Patt), fine embroidery needles, natural herbal dyes.',
    makingProcess: '1. Pahari miniature artist sketches classical composition on fine cotton cloth with charcoal. 2. Embroiderer fills designs using untwisted silk floss without knots. 3. Reversible Dorukha satin stitch applied so both front and reverse sides are flawless. 4. Outlines enclosed with fine black thread.',
    traditionalProducts: 'Square rumal wall hangings, ceremonial gift wrappers, cushion covers, framed art panels.',
    modernContext: 'Awarded GI tag in 2008. The Delhi Crafts Council and Himachal Handloom Corporation run preservation ateliers to train young women artisans.',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 10. JHARKHAND - Sohrai & Khovar Painting
  {
    name: 'Sohrai & Khovar Painting',
    localName: 'सोहराई और कोहवर कला / Hazaribagh Tribal Murals',
    state: 'Jharkhand',
    region: 'Chota Nagpur Plateau',
    district: 'Hazaribagh',
    place: 'Hazaribagh & surrounding villages',
    type: 'Traditional Mud Wall & Indigenous Folk Painting',
    originPeriod: 'Origin period: Believed to date back to prehistoric times; linked stylistically to Mesolithic rock art caves in Isko, Hazaribagh.',
    history: 'Sohrai is an indigenous harvest festival art, while Khovar is a bridal chamber ceremonial art. Practiced by women of Santhal, Munda, Oraon, and Kurmi tribes on mud walls of their cottages, painting animals, birds, and fertility symbols using natural soils.',
    culturalSignificance: 'Sohrai celebrates livestock and gratitude to cattle post-harvest, while Khovar celebrates fertility, matrimonial bliss, and maternal protection.',
    culturalBackground: 'Tribal women artists using ancient sgraffito-like combing and finger-swiping techniques passed from mother to daughter.',
    materials: 'Charcoal black earth (Mangar soil), red haematite earth (Geru), yellow earth (Nagri), white kaolin clay (Dhudhi matti), broken combs, and chewing-stick toothbrushes (datun).',
    makingProcess: '1. Wall covered with wet black mud. 2. Coat of white kaolin plaster applied over black layer. 3. While top layer is wet, broken comb or fingertips scrape away white slip to reveal dark patterns beneath (sgraffito). 4. Sun-dried naturally.',
    traditionalProducts: 'Harvest festival murals, framed paper paintings, terracotta vases, hand-painted sarees.',
    modernContext: 'Received Geographical Indication (GI) registration in 2020. Conservation spearheaded by environmentalist Bulu Imam and tribal women cooperatives.',
    coverImage: 'https://images.unsplash.com/photo-1579783901586-d88db74b4fe4?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 11. KARNATAKA - Channapatna Toys (Detailed Feature Entry)
  {
    name: 'Channapatna Toys',
    localName: 'ಚನ್ನಪಟ್ಟಣದ ಗೊಂಬೆಗಳು / चन्नपटना खिलौने',
    state: 'Karnataka',
    region: 'South Karnataka / Cauvery Basin',
    district: 'Ramanagara',
    place: 'Channapatna',
    type: 'Traditional Woodcraft, Turning & Lacquerware',
    originPeriod: 'Origin period: Believed to date back to the late 18th century CE under the patronage of ruler Tipu Sultan.',
    history: 'Channapatna is celebrated across India as "Gombegala Ooru" (Town of Toys). Historical records substantiate that Tipu Sultan, seeking to foster indigenous craftsmanship in Mysore, invited master artisans from Persia to train local woodcarvers in the delicate art of lathe-turned lacquerware. The craft subsequently matured into an iconic heritage industry using natural, non-toxic wood and vegetable lacquer.',
    culturalSignificance: 'Channapatna toys are renowned for being 100% child-safe and non-toxic. Traditionally presented to children during Dasara festivities and arranged in the festive Bombe Habba display. The smooth curved surfaces and glowing lacquer colors reflect traditional Kannada festive joy.',
    culturalBackground: 'Artisanal community comprised of the Vokkaliga, Muslim, and diverse artisan families operating lathe workshops across Ramanagara district.',
    materials: 'Ivory wood (Wrightia tinctoria / Aale mara), natural button lac, natural vegetable dye pigments (turmeric for yellow, kumkum/madder for red, indigo for blue, and katha for brown), and dried Talegari (screw pine / Pandanus) leaves for polishing.',
    makingProcess: '1. Seasoning: Ivory wood logs are seasoned naturally in shade for several months. 2. Lathe turning: Wood is mounted onto hand or motorized lathes and turned with chisels into circular profiles. 3. Lacquer preparation: Button lac is heated and blended with natural non-toxic vegetable dyes to form colored lacquer sticks. 4. Lacquering: While the wooden piece spins rapidly on the lathe, the lacquer stick is pressed against it; frictional heat melts and applies the lac evenly. 5. Burnishing: Dried Talegari (screw pine) leaves are pressed against the spinning object to polish it to a glossy, glass-like shine without chemical varnishes.',
    traditionalProducts: 'Raja-Rani royal dolls, wooden rocking horses, spinning tops (Buguri), mathematical beads, rocking toys, keychains, and modern educational puzzles.',
    modernContext: 'Awarded India’s early Geographical Indication (GI) status in 2006. Modern initiatives backed by the Karnataka State Handicrafts Development Corporation (KSHDC) and design institutes have introduced contemporary ergonomic toys while safeguarding the century-old non-toxic vegetable lacquer formulation.',
    coverImage: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },
  {
    name: 'Bidriware',
    localName: 'ಬಿದ್ರಿ ಕಲೆ / बिदरी शिल्प',
    state: 'Karnataka',
    region: 'Kalyana Karnataka / North Karnataka',
    district: 'Bidar',
    place: 'Bidar',
    type: 'Metal Inlay Craft',
    originPeriod: 'Origin period: Believed to date back to the 14th–15th century CE under the Bahmani Sultanate.',
    history: 'Developed under the patronage of the Bahmani Sultans of Bidar. The craft was introduced by master metalworkers brought from Shiraz and Tabriz in Iran, fusing Persian inlay motifs with indigenous Deccan metalwork.',
    culturalSignificance: 'Historically presented as royal gifts and treasured in royal courts for its striking contrast of pure silver against lustrous jet-black zinc alloy.',
    culturalBackground: 'Hereditary craft of artisan families in Bidar, who uniquely utilize historical soil taken from the Bidar Fort grounds for oxidation.',
    materials: 'Zinc and copper alloy (16:1 ratio), pure silver wire and sheets, and special Bidar Fort soil mixed with ammonium chloride.',
    makingProcess: '1. Casting: Base object cast from zinc-copper alloy. 2. Etching: Artisans engrave intricate patterns with steel chisels. 3. Inlay (Tarkashi): Pure silver wire or thin sheet hammered into engravings. 4. Polishing: Surface smoothened with carborundum stones. 5. Blackening: Dipped in warm mixture of Bidar fort soil and ammonium chloride which oxidizes zinc to deep jet black while leaving silver brilliant.',
    traditionalProducts: 'Hookah bases, Aftaba water jugs, jewelry boxes, cufflinks, plates.',
    modernContext: 'GI tagged in 2006; supported by the Karnataka Handicrafts Development Corporation.',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 12. KERALA - Aranmula Kannadi
  {
    name: 'Aranmula Kannadi',
    localName: 'ആറന്മുളക്കണ്ണാടി / आराण्मुल धातु दर्पण',
    state: 'Kerala',
    region: 'Central Travancore',
    district: 'Pathanamthitta',
    place: 'Aranmula',
    type: 'Traditional Metal Mirror Metallurgy',
    originPeriod: 'Origin period: Believed to date back to the 18th century CE under the patronage of the Royal King of Chempakassery.',
    history: 'Aranmula Kannadi is a handmade metal alloy mirror, not made of glass. A family of bronze smiths brought from Tamil Nadu to build the sacred Aranmula Parthasarathy Temple discovered the secret alloy formulation that produces perfect optical reflection from front surface reflection rather than silvered glass back-reflection.',
    culturalSignificance: 'One of the eight auspicious items (Ashtamangalyam) essential for traditional Kerala weddings, housewarmings, and Vishu festival arrangements. Associated with Goddess Lakshmi.',
    culturalBackground: 'Confined to a close hereditary clan of master bronze smiths in Aranmula village.',
    materials: 'Secret proprietary alloy of copper and tin (bell metal alloy), brass filigree frame, polishing clay, and velvet cloth.',
    makingProcess: '1. Molten copper-tin alloy poured into two-piece clay mold. 2. Cast alloy blank cooled and cut. 3. Polished continuously by hand for days using velvet cloth dipped in fine emery paste until an optical mirror finish is obtained. 4. Mounted in ornamental brass frame with holy conch or peacock motifs.',
    traditionalProducts: 'Vaalkannadi (handled mirror), Stand mirror, Royal ceremonial mirrors.',
    modernContext: 'Granted GI status in 2004–05. Celebrated globally as a metallurgical marvel of ancient Indian chemistry.',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 13. MADHYA PRADESH - Gond Art
  {
    name: 'Gond Tribal Art',
    localName: 'गोंड चित्रकला / Gond Painting of Patangarh',
    state: 'Madhya Pradesh',
    region: 'Narmada Valley / Mahakoshal',
    district: 'Dindori & Mandla',
    place: 'Patangarh',
    type: 'Tribal Painting & Folk Art',
    originPeriod: 'Origin period: Believed to date back several centuries as traditional home mud-wall painting; gained contemporary paper canvas prominence in the 1980s.',
    history: 'The Gond tribe is one of India’s largest indigenous communities. Traditionally, the Pardhan Gonds painted dwellings during festivals with "Digna" geometric patterns and folk tales. Modern Gond painting gained international stature through master artist Jangarh Singh Shyam in Patangarh.',
    culturalSignificance: 'Rooted in the belief that looking at auspicious images brings good fortune. Animals, trees, and spirits are depicted with signature micro-patterns (dots, dashes, fine curves) unique to each artist family.',
    culturalBackground: 'Pardhan Gond community residing in the forested regions of Dindori and Mandla districts.',
    materials: 'Natural colors from coloured soils, charcoal, cow dung, leaves, modern canvas and acrylics.',
    makingProcess: '1. Base canvas or paper prepared. 2. Outer structural silhouettes sketched. 3. Primary bright color fields blocked in. 4. Signature repetitive micro-lines, dots, or fish-scale strokes painstakingly filled across all forms to create visual vibration.',
    traditionalProducts: 'Canvas paintings, ceremonial wall art, illustrated story books, home decor panels.',
    modernContext: 'Awarded GI tag in 2023. Exhibited in major modern art museums globally including Paris, Tokyo, and London.',
    coverImage: 'https://images.unsplash.com/photo-1582560475093-ba66accbc424?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 14. MAHARASHTRA - Warli Folk Art
  {
    name: 'Warli Painting',
    localName: 'वारली चित्रकला / Warli Tribal Art',
    state: 'Maharashtra',
    region: 'North Konkan / Sahyadri Range',
    district: 'Palghar & Thane',
    place: 'Dahanu & Jawhar',
    type: 'Traditional Tribal Wall Painting',
    originPeriod: 'Origin period: Believed to date back to the 10th century CE or earlier, retaining stylistic continuity from Neolithic cave paintings (c. 2500–3000 BCE).',
    history: 'The Warli tribe residing in the mountainous and coastal border areas of Maharashtra practice this vivid geometric art. Traditionally executed by married women (Savasinis) on the mud walls of marriage huts to welcome the fertility goddess Palghat.',
    culturalSignificance: 'Depicts harmony between man and nature. The iconic spiral circle dance (Tarpa dance) symbolizes the circle of life without beginning or end.',
    culturalBackground: 'Warli indigenous tribal community inhabiting Palghar and Thane districts.',
    materials: 'Red ochre (Geru) and cow dung mud base, rice paste binder, water, and chewed bamboo twigs used as fine brushes.',
    makingProcess: '1. Mud walls plastered with cow dung and red clay wash. 2. Rice flour soaked in water and gum binder. 3. Bamboo twig chewed at one tip to form natural bristles. 4. Fundamental geometric vocabulary (circle, triangle, square) used to construct human, animal, and nature figures.',
    traditionalProducts: 'Lagana chitra (wedding murals), cloth paintings, terracotta pots, bamboo lamps.',
    modernContext: 'Registered under GI in 2014. Pioneer Jivya Soma Mashe brought global acclaim, earning the Padma Shri.',
    coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 15. MANIPUR - Longpi Black Stone Pottery
  {
    name: 'Longpi Black Stone Pottery',
    localName: 'ലോങ്പി മൺപാത്രങ്ങൾ / लोंगपी काली मिट्टी के बर्तन (Loree Ham)',
    state: 'Manipur',
    region: 'Ukhrul Hills',
    district: 'Ukhrul',
    place: 'Longpi (Nungbi)',
    type: 'Traditional Coil Pottery without Potter’s Wheel',
    originPeriod: 'Origin period: Believed to date back to antiquity; practiced as a living stone craft by the Tangkhul Naga tribe for centuries.',
    history: 'Crafted exclusively in Longpi village by the Tangkhul Naga people, this pottery is uniquely crafted without using a potter’s wheel. The material is a special mixture of weathered serpentine rock and special clay found only along riverbeds in Longpi.',
    culturalSignificance: 'Regarded as royal earthenware in ancient Manipur, used for grand festive banquets and ritual meat stews. Known for exceptional heat retention and imparting earthy flavor.',
    culturalBackground: 'The Tangkhul Naga tribal community of Longpi village.',
    materials: 'Serpentine rock crushed into fine gravel, weathered brown clay, water, and fresh Machhi leaves for black polish.',
    makingProcess: '1. Serpentine stone crushed and sieved. 2. Blended with river clay in 1:1 ratio. 3. Rolled into slabs and shaped entirely with hands, wooden bats, and bamboo molds without a wheel. 4. Sun-dried and kiln-fired outdoors. 5. While red-hot from fire, rubbed with local Machhi leaves to impart natural jet-black lustrous finish.',
    traditionalProducts: 'Cooking kettles, tea pots, serving bowls, cups, contemporary casseroles.',
    modernContext: 'GI tagged under Manipur; highly favored by modern eco-conscious chefs for natural induction-compatible toxin-free cookware.',
    coverImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 16. MEGHALAYA - Cane and Bamboo Craft
  {
    name: 'Meghalaya Cane & Bamboo Weaving',
    localName: 'मेघालय बेंत और बांस शिल्प / Khasi Bamboo Craft',
    state: 'Meghalaya',
    region: 'Khasi and Jaintia Hills',
    district: 'East Khasi Hills & Ri-Bhoi',
    place: 'Sohra (Cherrapunji) & Nongpoh',
    type: 'Traditional Cane & Bamboo Basketry',
    originPeriod: 'Origin period: Believed to date back several centuries, integral to the lifestyle and architecture of the Khasi, Jaintia, and Garo tribes.',
    history: 'Meghalaya’s wet rainforest terrain provided abundant natural bamboo and wild cane. Indigenous tribes mastered intricate split-bamboo weaving to construct weather-resistant shelters, rain shields, and bridges.',
    culturalSignificance: 'The "Knup", an indigenous woven bamboo rain-shield worn over the head, allows farmers to harvest crops during monsoon downpours in Cherrapunji and Mawsynram.',
    culturalBackground: 'Khasi, Jaintia, and Garo indigenous tribal communities.',
    materials: 'Wild cane (Calamus spp.), mature Bambusa bamboo, natural resin binders.',
    makingProcess: '1. Bamboo harvested after rainy season and seasoned against insects. 2. Splinters sliced into paper-thin strips using a specialized dao (machete). 3. Hand-woven in hexagonal and twill patterns. 4. Smoked over hearth fire for durability.',
    traditionalProducts: 'Knup rain-shields, Moora stools, Khasi carrying baskets (Khoh), floor mats, fish traps.',
    modernContext: 'Promoted actively by the North Eastern Handicrafts and Handlooms Development Corporation for sustainable zero-plastic lifestyle goods.',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 17. MIZORAM - Puan Handloom Weaving
  {
    name: 'Mizo Puan Handloom Weaving',
    localName: 'मिज़ो पुआन हथकरघा / Mizo Traditional Puan',
    state: 'Mizoram',
    region: 'Lushai Hills',
    district: 'Aizawl & Thenzawl',
    place: 'Thenzawl',
    type: 'Traditional Handloom & Loin-Loom Weaving',
    originPeriod: 'Origin period: Documented since ancient tribal settlements in the Lushai hills; codified during the 18th century CE.',
    history: 'Thenzawl is the handloom heartland of Mizoram. The Puan is the soul of Mizo women’s heritage, woven on traditional backstrap loin-looms and fly-shuttle frame looms. Distinct varieties like Puanchei, Ngotekherh, and Tawlhlohpuan signify specific cultural statuses.',
    culturalSignificance: 'Puanchei is the most colorful festive bridal costume, worn during Cheraw (bamboo dance) and Chapchar Kut festivals.',
    culturalBackground: 'Hereditary skill among Mizo women, passed down as a mark of cultural identity and artistry.',
    materials: 'Fine combed cotton yarns, spun acrylic silk, traditional vegetable dyes.',
    makingProcess: '1. Cotton warp mounted on loin loom or frame loom. 2. Weft yarns hand-inserted with intricate geometric picks. 3. Distinct colored stripes and diamond motifs created using extra-weft insertion technique.',
    traditionalProducts: 'Puanchei, Ngotekherh, Hmaram, Tawlhlohpuan, traditional shawls.',
    modernContext: 'Multiple Mizo Puans have received GI registration (Puanchei, Ngotekherh, Tawlhlohpuan); supported by Mizoram Handloom Apex Society.',
    coverImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 18. NAGALAND - Naga Shawl Weaving & Woodcraft
  {
    name: 'Naga Shawl Weaving',
    localName: 'नागा पारंपरिक शॉल / Naga Loin Loom Shawls',
    state: 'Nagaland',
    region: 'Naga Hills',
    district: 'Kohima, Mon & Mokokchung',
    place: 'Kohima & Khonoma',
    type: 'Traditional Loin Loom Weaving',
    originPeriod: 'Origin period: Practiced for centuries; distinct motifs formalized according to tribal clans over generations.',
    history: 'Every Naga tribe (Angami, Ao, Lotha, Konyak, Sumi) has its own distinct shawl design. In ancient times, wearing specific warrior shawls (such as the Tsungkotepsu of the Aos) was an honor earned through bravery or generosity in community feasts.',
    culturalSignificance: 'More than a garment, a Naga shawl is a social badge indicating the wearer’s clan, social standing, and valor. Displayed with reverence at the Hornbill Festival.',
    culturalBackground: 'Master women weavers belonging to the 16 major tribes of Nagaland.',
    materials: 'Local indigenous tree-cotton, spun wild nettle fiber, wool, natural madder and bark dyes.',
    makingProcess: '1. Cotton hand-spun on drop spindles. 2. Dyed with wild roots and tree bark. 3. Woven on traditional backstrap loin loom where the weaver’s body tension regulates warp tightness. 4. Motifs of tigers, mithun heads, and spears embroidered with extra weft.',
    traditionalProducts: 'Tsungkotepsu shawl, Rongsu shawl, Angami Loramhoushu, warrior wraps.',
    modernContext: 'Protected with GI registrations for multiple Naga shawls; promoted at international fashion platforms.',
    coverImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 19. ODISHA - Raghurajpur Pattachitra
  {
    name: 'Odisha Pattachitra',
    localName: 'ଓଡ଼ିଶା ପଟ୍ଟଚିତ୍ର / ओडिशा पट्टचित्र',
    state: 'Odisha',
    region: 'Coastal Odisha',
    district: 'Puri',
    place: 'Raghurajpur Heritage Village',
    type: 'Traditional Cloth Scroll Painting',
    originPeriod: 'Origin period: Believed to date back to the 12th century CE, evolving alongside the cult of Lord Jagannath at Puri.',
    history: 'Raghurajpur near Puri is an acclaimed living heritage village where every family is an artist (Chitrakar). Pattachitra evolved from temple rituals where paintings of Jagannath, Balabhadra, and Subhadra (Anasara Patti) substituted for the deities during their holy isolation.',
    culturalSignificance: 'Sacred scroll art that depicts the divine Leelas of Krishna, Dasavatara, and Ramayana with flowing lines, vibrant natural colors, and ornamental floral borders.',
    culturalBackground: 'Hereditary Chitrakar artisan community of Raghurajpur and Puri.',
    materials: 'Old cotton cloth, tamarind seed gum (Niryas), conch-shell powder (Sankha), hingula (cinnabar), haritala (orpiment), lampblack, and mongoose hair brushes.',
    makingProcess: '1. Two layers of cotton glued with tamarind paste and coated with soft stone and conch-shell powder. 2. Canvas rubbed with stones to glossy porcelain smoothness. 3. Direct red outline sketch drawn with fine brush. 4. Bright primary natural colors filled in. 5. Protected with heated natural lac tree resin coating.',
    traditionalProducts: 'Puri temple hanging scrolls, palm leaf engravings (Tala Pattachitra), painted coconuts, wooden tusser hangings.',
    modernContext: 'GI registered in 2008. Raghurajpur is recognized as India’s first Heritage Crafts Village by the Ministry of Tourism.',
    coverImage: 'https://images.unsplash.com/photo-1582560475093-ba66accbc424?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 20. PUNJAB - Phulkari Embroidery
  {
    name: 'Phulkari Embroidery',
    localName: 'ਫੁਲਕਾਰੀ / फुलकारी कशीदाकारी',
    state: 'Punjab',
    region: 'Majha and Malwa',
    district: 'Patiala, Amritsar & Bathinda',
    place: 'Patiala',
    type: 'Traditional Silk Floss Embroidery',
    originPeriod: 'Origin period: Documented in Punjabi folklore and Waris Shah’s Heer Ranjha (18th century CE); believed to date back earlier.',
    history: 'Phulkari, meaning "flower work", is the traditional needlework of Punjab. Mothers and grandmothers embroidered coarse cotton khaddar cloth with untwisted silk floss (pat) from the reverse side to prepare bridal veils for future brides.',
    culturalSignificance: 'A sacred cultural gift imbued with maternal blessings. Distinct varieties include Choap (presented by maternal grandmother), Bagh (all-over garden embroidery), and Sainchi.',
    culturalBackground: 'Rural Punjabi women across Majha, Malwa, and Doaba regions.',
    materials: 'Coarse homespun cotton (Khaddar), untwisted silk floss (Pat) from Kashmir, fine embroidery needles.',
    makingProcess: '1. Rust-red or indigo homespun khaddar selected. 2. Pattern embroidered strictly from the reverse side by counting warp and weft threads without tracing. 3. Darning stitch creates long lustrous satin blocks on front.',
    traditionalProducts: 'Bagh duppattas, Choap bridal shawls, jackets, cushion covers.',
    modernContext: 'Jointly awarded GI tag across Punjab, Haryana, and Rajasthan in 2011. Celebrated in Punjabi cultural festivals worldwide.',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 21. RAJASTHAN - Jaipur Blue Pottery & Molela Terracotta (Detailed Region Distinction)
  {
    name: 'Jaipur Blue Pottery',
    localName: 'जयपुर ब्लू पॉटरी / Blue Pottery of Jaipur',
    state: 'Rajasthan',
    region: 'Dhundhar',
    district: 'Jaipur',
    place: 'Jaipur',
    type: 'Glazed Ceramic & Quartz Pottery',
    originPeriod: 'Origin period: Believed to date back to the early 19th century CE under the patronage of Maharaja Sawai Ram Singh II.',
    history: 'Jaipur Blue Pottery is unique because it uses no clay whatsoever. Originating from Turko-Persian traditions, it was introduced to Jaipur when Maharaja Sawai Ram Singh II sent local potters to Delhi to learn the technique from Persian masters.',
    culturalSignificance: 'Adorns Jaipur royal palaces (City Palace, Rambagh) and temples with turquoise-blue arabesque flora, birds, and Mughal motifs.',
    culturalBackground: 'Kumbhar and artisan families of Jaipur, revitalized in the 20th century by visionary artist Kripal Singh Shekhawat.',
    materials: 'Ground quartz stone, glass (cullet), Fuller’s earth (Multani mitti), gum, copper oxide (for turquoise blue), and cobalt oxide (for deep dark blue).',
    makingProcess: '1. Quartz powder, glass, and gum kneaded with water into dough. 2. Rolled into flat sheets and pressed into open plaster molds. 3. Cleaned and coated with white slip. 4. Delicate floral patterns painted freehand with cobalt and copper oxides. 5. Glazed with mixture of borax and quartz. 6. Fired once in wood-fired kilns at 800–850°C.',
    traditionalProducts: 'Decorative plates, vases, door knobs, tile murals, bowls.',
    modernContext: 'GI registered in 2008. Eco-friendly lead-free glazes developed to enable functional dinnerware exports.',
    coverImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },
  {
    name: 'Molela Terracotta Plaques',
    localName: 'मोलेला टेराकोटा शिल्प / Molela Clay Murals',
    state: 'Rajasthan',
    region: 'Mewar',
    district: 'Rajsamand (near Udaipur)',
    place: 'Molela village',
    type: 'Hollow Relief Terracotta Craft',
    originPeriod: 'Origin period: Believed to date back several centuries; oral tradition links it to local tribal worship of deity Dharmaraja.',
    history: 'Situated on the banks of the Banas river in the Mewar region near Udaipur, Molela is home to a community of Kumhars who hand-model hollow terracotta relief plaques dedicated to folk deities like Devnarayan and Nagaraja.',
    culturalSignificance: 'Bhil and Garasia tribal devotees journey from hundreds of kilometers during Magh month with their village priests (Bhopas) to purchase consecrated Molela plaques for their village shrines.',
    culturalBackground: 'The Kumhar (potter) community residing exclusively in Molela village in the Mewar region.',
    materials: 'Clay dug from the Banas riverbed, donkey dung (serving as natural organic temper), natural mineral slip (Peli mitti, Geru).',
    makingProcess: '1. Banas river clay mixed with donkey dung in precise proportions. 2. Clay rolled flat onto floor. 3. Sculptor builds hollow relief deity figurines using only thumbs and small bamboo spatula without molds. 4. Dried in shade. 5. Baked in open wood kilns. 6. Painted with bright water tempera colors.',
    traditionalProducts: 'Votive deity plaques (Devnarayan, Nagaraja, Chamunda), architectural wall murals.',
    modernContext: 'GI tagged under Rajasthan; sought-after by contemporary architects for rustic terra-cotta facades.',
    coverImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 22. SIKKIM - Choktse Wooden Folding Tables
  {
    name: 'Sikkim Choktse Wood Carving',
    localName: 'चोक्त्से काष्ठ शिल्प / Tibetan Carved Folding Tables',
    state: 'Sikkim',
    region: 'East Sikkim',
    district: 'Gangtok',
    place: 'Gangtok',
    type: 'Traditional Buddhist Wood Carving & Furniture',
    originPeriod: 'Origin period: Believed to date back to the 17th century CE with the arrival of Buddhist Chogyal monarchy.',
    history: 'Choktse is a traditional Tibetan-Sikkimese foldable wooden table meticulously hand-carved with auspicious Mahayana Buddhist motifs. Developed to furnish monasteries and aristocratic homes in the Himalayan kingdom.',
    culturalSignificance: 'Used during Buddhist prayer ceremonies to hold prayer bowls, holy scriptures, and butter lamps. The carvings feature the Eight Auspicious Symbols (Ashtamangala) and mythological dragons.',
    culturalBackground: 'Bhutia and Lepcha master woodcarvers trained through traditional monastic apprentice schools.',
    materials: 'Himalayan softwoods (such as tooni, cedar, and pine), mineral paints, gold leafing, and clear protective lacquer.',
    makingProcess: '1. Wood blocks dried and cut to size. 2. Intricate dragons, snow lions, and lotus motifs traced. 3. Deep relief wood carving executed with specialized gouges. 4. Table assembled with collapsible folding hinges. 5. Hand-painted in rich jewel tones and highlighted with pure gold enamel.',
    traditionalProducts: 'Choktse tables, prayer book stands, altars, dragon wall plaques.',
    modernContext: 'Protected and taught at the Directorate of Handicrafts and Handlooms (DHH) in Gangtok.',
    coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 23. TAMIL NADU - Tanjore Painting & Swamimalai Bronze
  {
    name: 'Tanjore Painting',
    localName: 'தஞ்சாவூர் ஓவியம் / तंजौर चित्रकला',
    state: 'Tamil Nadu',
    region: 'Cauvery Delta / Chola Nadu',
    district: 'Thanjavur',
    place: 'Thanjavur',
    type: 'Gold Foil Inlay & Panel Painting',
    originPeriod: 'Origin period: Believed to date back to the 16th–17th century CE under the Thanjavur Nayakas and Maratha rulers.',
    history: 'Thanjavur painting flourished under the patron kings of the Vijayanagara, Nayaka, and Maratha dynasties of Tanjore. Characterized by dense compositions, glowing 22-carat gold foil leafing, and embedded semi-precious stones (Jaipur stones).',
    culturalSignificance: 'Serves as devotional icons in South Indian puja rooms. Depictions focus primarily on child Krishna (Navaneetha Krishna), Goddess Lakshmi, Rama Pattabhishekam, and Shiva.',
    culturalBackground: 'Raju and Naidu artisanal communities of Thanjavur and Tiruchirappalli.',
    materials: 'Teakwood wooden board, unbleached cloth, Arabic gum, chalk powder (muck paste), 22-karat pure gold foil leaf, semi-precious gems.',
    makingProcess: '1. Board covered with cotton cloth pasted with tamarind glue. 2. Chalk powder and Arabic gum paste (muck) applied to build relief elements. 3. Semi-precious stones embedded. 4. Pure 22-carat gold foil sheets pressed over relief areas. 5. Figures painted with rich water colors.',
    traditionalProducts: 'Framed devotional altar panels, wedding gifts, miniature icons.',
    modernContext: 'GI tagged in 2007–08. Regarded as one of India’s most luxurious and enduring classical devotional art forms.',
    coverImage: 'https://images.unsplash.com/photo-1582560475093-ba66accbc424?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 24. TELANGANA - Pochampally Ikat & Pembarthi Metal
  {
    name: 'Pochampally Ikat',
    localName: 'పోచంపల్లి ఇక్కత్ / पोचमपल्ली इकत (Pagdu Bandhu)',
    state: 'Telangana',
    region: 'Nalgonda / Yadadri',
    district: 'Yadadri Bhuvanagiri',
    place: 'Bhoodan Pochampally',
    type: 'Double Ikat Textile Weaving',
    originPeriod: 'Origin period: Believed to date back to the early 19th century CE; rooted in ancient resist-dye traditions.',
    history: 'Bhoodan Pochampally is globally famous as the "Silk City of India". The craft utilizes the intricate "Double Ikat" technique, where both warp and weft yarns are tied and dyed in precision geometric patterns before being loaded onto the loom.',
    culturalSignificance: 'Worn proudly by women across Telangana and Andhra Pradesh during festivals and weddings; famed for distinct geometric clarity and silky fall.',
    culturalBackground: 'Padmashali and Devanga traditional weaver communities.',
    materials: 'Pure mulberry silk, natural cotton yarns, chemical and natural vat dyes, frame looms.',
    makingProcess: '1. Design drawn on graph paper. 2. Warp and weft threads wound on warping frames. 3. Bundles of thread tied with rubber strips to resist dye (Chitku process). 4. Dyed in color baths repeatedly. 5. Threads aligned on pit loom and hand-woven.',
    traditionalProducts: 'Pochampally silk sarees, dupattas, stoles, home furnishings.',
    modernContext: 'Awarded GI registration in 2005 (the very first traditional craft GI in undivided Andhra Pradesh). Recognized by UNESCO as a model craft tourism village.',
    coverImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 25. TRIPURA - Bamboo & Cane Crafts
  {
    name: 'Tripura Bamboo & Cane Fluting',
    localName: 'ত্রিপুরা বাঁশ ও বেত শিল্প / त्रिपुरा बांस एवं बेंत शिल्प',
    state: 'Tripura',
    region: 'Tripura Valley',
    district: 'West Tripura',
    place: 'Agartala',
    type: 'Traditional Bamboo Weaving & Screen Carving',
    originPeriod: 'Origin period: Practiced for centuries across indigenous tribal clans (Tripuri, Reang, Jamatia).',
    history: 'Tripura boasts over 21 indigenous species of bamboo. Artisans developed remarkably fine split-bamboo screens and mats with delicate fluting, historically used in royal palaces of the Manikya dynasty.',
    culturalSignificance: 'From cradle to grave, bamboo touches every stage of tribal life in Tripura. Used for constructing houses, traditional instruments, fishing traps, and sacred altars.',
    culturalBackground: 'Tripuri, Chakma, and Bengali artisan communities of Agartala and Khowai.',
    materials: 'Muli bamboo (Melocanna baccifera), Barak bamboo, cane, natural varnishes.',
    makingProcess: '1. Green bamboo felled and soaked to prevent borer attack. 2. Splinters sliced paper-thin. 3. Woven into fine gossamer-thin screens or rolled into rigid structures.',
    traditionalProducts: 'Delicate bamboo window screens, lamp shades, fruit bowls, hand fans, furniture.',
    modernContext: 'Recognized for world-class sustainability; supported by Tripura Bamboo Mission.',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 26. UTTAR PRADESH - Varanasi Zardozi & Banarasi Brocade
  {
    name: 'Varanasi Zardozi & Banarasi Brocade',
    localName: 'बनारसी ज़री और ब्रोकेड / Banarasi Zari Silk Weaving',
    state: 'Uttar Pradesh',
    region: 'Purvanchal',
    district: 'Varanasi',
    place: 'Varanasi (Kashi)',
    type: 'Zari Brocade Weaving & Metallic Embroidery',
    originPeriod: 'Origin period: Documented in ancient Vedic texts and Buddhist Jatakas; enriched during the Mughal era under Emperor Akbar (16th century CE).',
    history: 'Varanasi is one of the world’s oldest living cities. The synthesis of ancient Hindu silk-weaving traditions with Persian gold-wire brocade techniques created Banarasi silk brocade, famed for its golden zari metallic weave.',
    culturalSignificance: 'The quintessential Indian bridal trousseau saree. Motifs like Kalka (mango), Shikargah (hunting scene), and floral Jal reflect regal opulence.',
    culturalBackground: 'Master Ansari weaver families living in the historic weavers’ quarters (Madanpura and Bajardiha) of Varanasi.',
    materials: 'Pure mulberry silk, gold and silver electroplated zari threads, jacquard punch cards.',
    makingProcess: '1. Naksha (design) created on grid paper. 2. Punch cards prepared for jacquard attachment. 3. Silk warp dyed and warped. 4. Three weavers often sit together on pit loom: one operating shuttle, two guiding gold zari weft.',
    traditionalProducts: 'Banarasi silk sarees, bridal lehengas, dupattas, brocade stoles.',
    modernContext: 'GI registered in 2009. Protected by the Ministry of Textiles against cheap synthetic powerloom imitations.',
    coverImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 27. UTTARAKHAND - Aipan Folk Art
  {
    name: 'Aipan Ritual Art',
    localName: 'ऐपण कला / Kumaoni Aipan Floor & Wall Art',
    state: 'Uttarakhand',
    region: 'Kumaon Hills',
    district: 'Almora & Nainital',
    place: 'Almora',
    type: 'Traditional Ritual Floor & Wall Art',
    originPeriod: 'Origin period: Believed to date back to the Chand dynasty (c. 10th–18th century CE) in Kumaon.',
    history: 'Aipan is an auspicious geometric ritual folk art practiced by women of the Kumaon region. Drawn on cleaned floors and doorsteps during festivals like Diwali, weddings, and naming ceremonies.',
    culturalSignificance: 'Symbolizes divinity, auspiciousness, and spiritual protection. Distinct motifs like Chowki, Lakshmi Padchinha (divine footprints), and Vasudhara invoke prosperity.',
    culturalBackground: 'Practiced by Kumaoni women across the hills of Almora, Nainital, and Pithoragarh.',
    materials: 'Red clay slip (Geru), soaked and ground rice paste (Biswar), applied with ring finger (Anamika).',
    makingProcess: '1. Ground or wooden chowki coated with deep red Geru paste and allowed to dry. 2. Soaked rice ground into fine white paste (Biswar). 3. Artist dips ring finger into Biswar and paints uninterrupted lines, dots, and sacred geometric yantras.',
    traditionalProducts: 'Puja Chowkis, temple doorway borders, wall scrolls, painted terracotta diyas.',
    modernContext: 'Granted GI status in 2021. Uttarakhand government runs the Aipan Girl initiative to promote female artisan entrepreneurship.',
    coverImage: 'https://images.unsplash.com/photo-1582560475093-ba66accbc424?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },

  // 28. WEST BENGAL - Kantha Embroidery & Bankura Terracotta
  {
    name: 'Bengal Kantha Embroidery',
    localName: 'কাঁথা শিল্প / कान्था कशीदाकारी',
    state: 'West Bengal',
    region: 'Rarh Region / Shantiniketan',
    district: 'Birbhum & Murshidabad',
    place: 'Bolpur & Shantiniketan',
    type: 'Traditional Running-Stitch Needlework',
    originPeriod: 'Origin period: Believed to date back to ancient times; documented in the Chaitanya Charitamrita (c. 16th century CE) and patronized by Rabindranath Tagore at Shantiniketan.',
    history: 'Kantha originated as an indigenous zero-waste upcycling craft where rural Bengali women layered old white cotton sarees and dhotis, stitching them together with colorful threads pulled from saree borders using simple running stitches (Nakshi Kantha).',
    culturalSignificance: 'Celebrates maternal love and oral folklore. Quilts were gifted to newborns and daughters at weddings, depicting lotus ponds, birds, village life, and mythological episodes.',
    culturalBackground: 'Rural Bengali women of Birbhum, Burdwan, and Murshidabad districts.',
    materials: 'Old or new soft white cotton/tussar silk, cotton threads in yellow, blue, red, green, and fine embroidery needles.',
    makingProcess: '1. Fabric layers spread and tacked together. 2. Motif outlines traced or drawn freehand. 3. Fine running stitch applied in ripples across entire background, creating characteristic quilted crinkle (ripple effect).',
    traditionalProducts: 'Nakshi Kantha quilts, stoles, sarees, pillow covers, wall tapestries.',
    modernContext: 'Awarded GI tag in 2008. Re-energized into high fashion worldwide by craft cooperatives in Shantiniketan.',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
  },
];
